import './globals.css'
import { Questrial } from 'next/font/google'

const font = Questrial({ subsets: ['latin'], weight: '400'})

export const metadata = {
  title: 'Hundred Flowers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
